name: CI Build Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate Tag
        id: meta
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Check Secret
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "USERNAME EMPTY"
            exit 1
          else
            echo "USERNAME FOUND"
          fi

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          cd TASK-6-Automate-Strapi-Deployment
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/strapi-task6:${{ steps.meta.outputs.tag }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/strapi-task6:${{ steps.meta.outputs.tag }}